apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: consumer-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Example consumer Acls for topic kafka-user-test
      - resource:
          type: topic
          name: kafka-user-test
          patternType: literal
        operations:
          - Read
        host: "*"